"Copy this over to ~/.vimrc"
"cp ./vimrc ~/.vimrc"

if has('persistent_undo')      "check if your vim version supports it
    set undofile                 "turn on the feature  
    set undodir=$HOME/.vim/undo  "directory where the undo files will be stored
endif     

filetype indent on
:set shiftwidth=4
:set tabstop=4
:set autoindent
:set smartindent
:set expandtab
